"""
Kod producenta Virdyn
"""

BodyNodes = [
    'Hips',
    'RightUpperLeg',
    'RightLowerLeg',
    'RightFoot',
    'RightToe',
    'LeftUpperLeg',
    'LeftLowerLeg',
    'LeftFoot',
    'LeftToe',
    'Spine',
    'Spine1',
    'Spine2',
    'Spine3',
    'Neck',
    'Head',
    'RightShoulder',
    'RightUpperArm',
    'RightLowerArm',
    'RightHand',
    'LeftShoulder',
    'LeftUpperArm',
    'LeftLowerArm',
    'LeftHand',
]


HandNodes_20_r = [
    'RightHand',
    'RightThumbFinger',
    'RightThumbFinger1',
    'RightThumbFinger2',
    'RightIndexFinger',
    'RightIndexFinger1',
    'RightIndexFinger2',
    'RightIndexFinger3',
    'RightMiddleFinger',
    'RightMiddleFinger1',
    'RightMiddleFinger2',
    'RightMiddleFinger3',
    'RightRingFinger',
    'RightRingFinger1',
    'RightRingFinger2',
    'RightRingFinger3',
    'RightPinkyFinger',
    'RightPinkyFinger1',
    'RightPinkyFinger2',
    'RightPinkyFinger3',
]

HandNodes_20_l = [
    'LeftHand',
    'LeftThumbFinger',
    'LeftThumbFinger1',
    'LeftThumbFinger2',
    'LeftIndexFinger',
    'LeftIndexFinger1',
    'LeftIndexFinger2',
    'LeftIndexFinger3',
    'LeftMiddleFinger',
    'LeftMiddleFinger1',
    'LeftMiddleFinger2',
    'LeftMiddleFinger3',
    'LeftRingFinger',
    'LeftRingFinger1',
    'LeftRingFinger2',
    'LeftRingFinger3',
    'LeftPinkyFinger',
    'LeftPinkyFinger1',
    'LeftPinkyFinger2',
    'LeftPinkyFinger3',
]

HandNodes_16_r = [
    'RightHand',
    'RightThumbFinger',
    'RightThumbFinger1',
    'RightThumbFinger2',
    'RightIndexFinger1',
    'RightIndexFinger2',
    'RightIndexFinger3',
    'RightMiddleFinger1',
    'RightMiddleFinger2',
    'RightMiddleFinger3',
    'RightRingFinger1',
    'RightRingFinger2',
    'RightRingFinger3',
    'RightPinkyFinger1',
    'RightPinkyFinger2',
    'RightPinkyFinger3',
]

HandNodes_16_l = [
    'LeftHand',
    'LeftThumbFinger',
    'LeftThumbFinger1',
    'LeftThumbFinger2',
    'LeftIndexFinger1',
    'LeftIndexFinger2',
    'LeftIndexFinger3',
    'LeftMiddleFinger1',
    'LeftMiddleFinger2',
    'LeftMiddleFinger3',
    'LeftRingFinger1',
    'LeftRingFinger2',
    'LeftRingFinger3',
    'LeftPinkyFinger1',
    'LeftPinkyFinger2',
    'LeftPinkyFinger3',
]